import React, { useState } from 'react';

function RideList({ rides, onRideBooked, infoMessage, setInfoMessage, authToken }) {
  const [bookingRideId, setBookingRideId] = useState(null);
  const handleBookRide = async (rideId) => { setBookingRideId(rideId); setInfoMessage(''); try { if (!authToken) { window.location.href = '/login'; setBookingRideId(null); return; } const response = await fetch(`/api/rides/${rideId}/book`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${authToken}` }, }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setInfoMessage('Ride booked successfully!'); onRideBooked(); } catch (error) { setInfoMessage(error.message); } finally { setBookingRideId(null); } };
  const formatDateTime = (isoString) => { if (!isoString) return 'Invalid date'; const options = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }; return new Date(isoString).toLocaleDateString(undefined, options); };
  return ( <div className="ride-list-container"> <h2>Available Rides</h2> {infoMessage && <p className="info-message">{infoMessage}</p>} <div className="ride-list"> {!rides || rides.length === 0 ? ( <p>No available rides at the moment.</p> ) : ( rides.map(ride => ( <div key={ride.id} className="ride-card"> <h3>{ride.origin} to {ride.destination}</h3> <p><strong>Driver:</strong> {ride.driverName}</p> <p><strong>Departure:</strong> {formatDateTime(ride.departureTime)}</p> <p><strong>Seats Available:</strong> {ride.availableSeats}</p> <p className="price">₹{ride.price}</p> <button className="book-button" onClick={() => handleBookRide(ride.id)} disabled={bookingRideId === ride.id}> {bookingRideId === ride.id ? 'Booking...' : 'Book Ride'} </button> </div> )) )} </div> </div> );
}
export default RideList;
